# -*- coding: utf-8 -*-
"""Aluno5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yTrAxwyQXZeYvvNAuP4r_wQYaFC6Y_YI
"""

import time
var = 0
while var <=5:
    print(var)
    time.sleep(2)
    var+=1

from time import sleep
itens=['lucas','davi','wollas','samuel']
for item in itens:
    print(item)
    sleep(2)

sala = ['Brasil',['norte',['amazonas',['manaus'],'Acre',['rio branco']]],
        ['nordeste'],['paraiba',['joao pessoa'],['pernambuco',['recife']]]]

sala = []
while len(sala) <=5:
    nome = str(input('informe um nome: '))
    sala.append(nome)
for nome in sala:   
    print(nome)

grupo = []
while len(grupo)<2:
    pessoa = str(input('adicione uma pessoa: '))
    grupo.append(pessoa)
    qtd = 0
    while qtd <= len(grupo):
        qtd+=1
    if len(grupo)<qtd:
        qtd-=1
print(qtd)

grupo = []
while True:
    acao = int(input('digite um para adicionar ou 2 para listar: '))
    if acao == 1:
        pessoa = str('adicione o nome: ')
        grupo.append(pessoa)
    elif acao == 2:
        qtd = 1
        for pessoa in grupo:
            print(f'{qtd}: {pessoa}')
            qtd+=1
        break

import random
tentativas = 0
chances = 5
nsecreto = random.randint(1,10)
print(nsecreto)
while chances >= 1:
    r=int(input('adivine o nomero: '))
    tentativas+=1
    chances-=1
    if r == nsecreto:
        print('acertou')
        break
    else:
        if chances >=1:
            print(f'tentativa {tentativas} - errou, o numero secreto nao è {r} ')
            print(f'voce ainda tem {chances} chances. ')
        else:
            print(f'tentativa {tentativas} - errou, o numero secreto nao e {r} ')
            print('acabaram as suas chances. ')